linters-settings:
  gocyclo:
    min-complexity: 30
  misspell:
    locale: US
  errcheck:
    exclude-functions:
      - fmt.Fprintf
      - fmt.Println

linters:
  disable-all: true
  enable:
    - goimports
    - unused
    - errcheck
    - gocognit
    - gocyclo
    - gofmt
    - govet
    - misspell
    - staticcheck
    - whitespace
